Sending
Thunder-Invader/Datastreams-nVisionVue pull request #11
Opened 2020-06-24 11:46 UTC by thijsje89

Added four pages: Select receiver, Add details, Review details, confirmation.

2020-06-24 11:53 UTC, Thunder-Invader commented on datastreams/src/components/Confirmation.vue
>      color: #37B4E5;
Use color from scss

2020-06-24 11:53 UTC, Thunder-Invader commented on datastreams/src/components/Privacy.vue
> +
Remove white space

2020-06-24 11:53 UTC, Thunder-Invader commented on datastreams/src/components/Progress.vue
> +
Remove whitespace

2020-06-24 11:54 UTC, Thunder-Invader commented on datastreams/src/components/ReceiverAdd.vue
> +
Remove whitespace

2020-06-24 11:54 UTC, Thunder-Invader commented on datastreams/src/components/ReceiverAdd.vue
> +
Remove whitespace

2020-06-24 11:54 UTC, Thunder-Invader commented on datastreams/src/components/ReceiverAdd.vue
> +
Remove whitespace

2020-06-24 11:54 UTC, Thunder-Invader commented on datastreams/src/components/ReceiverAdd.vue
> +
Remove whitespace

2020-06-24 12:00 UTC, Thunder-Invader requested changes

2020-06-24 12:00 UTC, Thunder-Invader commented on datastreams/src/components/ReceiverAdd.vue
> +
Remove whitespace

2020-06-24 12:00 UTC, Thunder-Invader commented on datastreams/src/components/ReceiverAdd.vue
> +
Remove whitespace

2020-06-24 12:00 UTC, Thunder-Invader commented on datastreams/src/components/ReceiverAdd.vue
> +
Remove whitespace

2020-06-24 12:00 UTC, Thunder-Invader commented on datastreams/src/components/SelectReceiver.vue
> +
Remove whitespace

2020-06-24 12:00 UTC, Thunder-Invader commented on datastreams/src/components/SelectReceiver.vue
> +
Remove whitespace

2020-06-24 12:00 UTC, Thunder-Invader commented on datastreams/src/components/SelectReceiver.vue
> +
Remove whitespace

2020-06-24 12:00 UTC, Thunder-Invader commented on datastreams/src/components/SelectReceiver.vue
> +
Remove whitespace

2020-06-24 12:00 UTC, Thunder-Invader commented on datastreams/src/components/SelectReceiver.vue
> +
Remove whitespace

2020-06-24 12:00 UTC, Thunder-Invader commented on datastreams/src/views/SendingPage.vue
> +
Remove whitespace

2020-06-24 12:00 UTC, Thunder-Invader commented on datastreams/src/components/Progress.vue
> +
Remove whitespace

2020-06-24 12:00 UTC, Thunder-Invader commented on datastreams/src/components/ReceiverAdd.vue
> +
Remove whitespace

2020-06-24 12:00 UTC, Thunder-Invader commented on datastreams/src/components/ReceiverAdd.vue
> +
Remove whitespace

2020-06-24 12:00 UTC, Thunder-Invader commented on datastreams/src/components/ReceiverAdd.vue
> +
Remove whitespace

2020-06-24 12:00 UTC, Thunder-Invader commented on datastreams/src/components/ReceiverAdd.vue
> +
Remove whitespace

2020-06-24 12:00 UTC, Thunder-Invader commented on datastreams/src/components/AddDetails.vue
> +  .component_adddetails {
create own scss file

2020-06-24 12:00 UTC, Thunder-Invader commented on datastreams/src/components/AddDocs.vue
> +
create own scss file

2020-06-24 12:00 UTC, Thunder-Invader commented on datastreams/src/components/CompletedMsg.vue
> +
create own scss file

2020-06-24 12:00 UTC, Thunder-Invader commented on datastreams/src/components/SelectReceiver.vue
> +
create own scss file

2020-06-24 12:00 UTC, Thunder-Invader commented on datastreams/src/views/SendingPage.vue
> +
create own scss file

2020-06-24 13:03 UTC, Joshua3011 requested changes

2020-06-24 13:03 UTC, Joshua3011 commented on datastreams/src/components/AddDetails.vue
> +      <div class="component bericht">
BEM-methodiek toepassen

2020-06-24 13:03 UTC, Joshua3011 commented on datastreams/src/components/AddDetails.vue
> +  .left-part {
🔢  whitespace moet weg hier (en dubbele class)

2020-06-24 13:03 UTC, Joshua3011 commented on datastreams/src/components/AddDetails.vue
> +  }
De focus state nesten in `.option`

2020-06-24 13:03 UTC, Joshua3011 commented on datastreams/src/components/AddDetails.vue
> +  }
Neston

2020-06-24 13:03 UTC, Joshua3011 commented on datastreams/src/components/AddDetails.vue
> +    color: #26a9e0;
Color variabele gebruiken

2020-06-24 13:03 UTC, Joshua3011 commented on datastreams/src/components/AddDetails.vue
> +    color: #85d6de;
Color variabele gebruiken

2020-06-24 13:03 UTC, Joshua3011 commented on datastreams/src/components/AddDocs.vue
> +        }
Gebruik maken van $fonts variabelen

2020-06-24 13:03 UTC, Joshua3011 commented on datastreams/src/components/CompletedMsg.vue
> +                <div class="completedmsg_content">
BEM-Methodiek toepassen

2020-06-24 13:03 UTC, Joshua3011 commented on datastreams/src/components/Privacy.vue
> +                    <div class="info">
BEM-Methodiek toepassen

2020-06-24 13:03 UTC, Joshua3011 commented on datastreams/src/components/Privacy.vue
> +    }
Neston

2020-06-24 13:03 UTC, Joshua3011 commented on datastreams/src/components/Progress.vue
> +    </div>
BEM-Methodiek toepassen

2020-06-24 13:03 UTC, Joshua3011 commented on datastreams/src/components/Progress.vue
> +    margin-bottom: 4px;
BEM-Methodiek toepassen + Eigen .scss file aanmaken

2020-06-24 13:03 UTC, Joshua3011 commented on datastreams/src/components/ReceiverAdd.vue
> +<template>
BEM-Methodiek toepassen op deze file

2020-06-24 13:03 UTC, Joshua3011 commented on datastreams/src/components/ReceiverAdd.vue
> +  }
Eigen .scss file maken

2020-06-24 13:03 UTC, Joshua3011 commented on datastreams/src/components/ReceiverAdd.vue
> +  .btn-form{
Toevoegen aan `_elements.scss`

2020-06-24 13:03 UTC, Joshua3011 commented on datastreams/src/components/SelectReceiver.vue
> +    <div class="wrapper">
BEM-Methodiek toepassen op deze file

2020-06-24 13:03 UTC, Joshua3011 commented on datastreams/src/components/SelectReceiver.vue
> +        background: rgba(80, 189, 232, 0.2);
Variabele gebruiken of aanmaken

2020-06-24 13:03 UTC, Joshua3011 commented on datastreams/src/scss/_typography.scss
> +
WhItEsPaCe WeGhaLeN

2020-06-24 13:03 UTC, Joshua3011 commented on datastreams/src/views/SendingPage.vue
> +      <Confirmation v-show="confirm" />
Van de ID's classes maken

2020-06-25 07:41 UTC, Thunder-Invader approved these changes

2020-06-25 07:48 UTC, merged